name: Deploy Site

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 14.21.3
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run tests
      - name: Run tests
        run: npm test

      # 5️⃣ Build React project
      - name: Build project
        run: npm run build

      # 6️⃣ Deploy to FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.URL }}
          username: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.PASS }}
          protocol: ftp
          local-dir: ./build       # Only upload production build
          server-dir: ${{ secrets.PATH }}
          include: |
            build/static/**
            build/images/**
            build/index.html
            build/asset-manifest.json
            build/robots.txt
            build/manifest.json
          # log-level: verbose    # optional

      # 7️⃣ Success message
      - name: Signal Success
        run: echo '---- DEPLOY SUCCESSFUL ---'