name: Deploy Site v2

on:
  workflow_dispatch:

jobs:
  check_condition:
    runs-on: ubuntu-latest
    outputs:
      should_continue: ${{ steps.changes.outputs.should_continue }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - id: changes
        run: |
          echo "Checking for changes in src/ or public/..."

          if git diff --name-only HEAD~1 HEAD | grep -E '^(src|public)/'; then
            echo "Changes detected."
            echo "should_continue=true" >> $GITHUB_OUTPUT
          else
            echo "no changes"
            echo "should_continue=false" >> $GITHUB_OUTPUT
          fi

  main_job:
    needs: check_condition
    if: ${{ needs.check_condition.outputs.should_continue == 'true' }}
    runs-on: ubuntu-latest
    container:
      image: node:14-buster     # Full Node 14 ecosystem just like in 2021
    steps:
      - run: echo "This job runs only if the condition was false."
    
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: build
          
  deploy:
    runs-on: ubuntu-latest
    needs: main_job

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: build

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.URL }}
          username: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.PASS }}
          protocol: ftp
          local-dir: ./build/
          exclude: |
            **                      
            !static/**              
            !images/**              
            !index.html             
            !asset-manifest.json    
            !robots.txt
            !manifest.json
          server-dir: ${{ secrets.PATH }}