name: Deploy Site

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04 

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 14.21.3
          # cache: 'npm'  #omit cache, for now

      # Downgrade npm to 8 (compatible with Node 14 and core-js)
      - name: Upgrade npm to 8
        run: npm install -g npm@8
        shell: bash

      # Install dependencies
      - name: Install dependencies
        run: npm ci --ignore-scripts

      # Set compatible jsdom v
      - name: Downgrade jsdom for CI (Node 14 compatibility)
        run: npm install --save-dev jsdom@19
      
      # Rebuild only the packages that need scripts to run mocha tests
      - name: Rebuild required packages
        run: |
          npm rebuild @babel/core
          npm rebuild @babel/register
          npm rebuild jsdom
          npm rebuild jsdom-global
      
      # Run unit tests
      - name: Run tests
        run: npm run test

      # Build React project
      - name: Build project
        run: npm run build
        shell: bash

      # Deploy to FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.URL }}
          username: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.PASS }}
          protocol: ftp
          local-dir: ./build       # Only upload production build
          server-dir: ${{ secrets.PATH }}
          include: |
            static/**
            images/**
            index.html
            asset-manifest.json
            robots.txt
            manifest.json
          # log-level: verbose    # optional

      # Success message
      - name: Signal Success
        run: echo '---- DEPLOY SUCCESSFUL ---'