name: Deploy Site

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Runner Environment
        run: |
          echo "=== SYSTEM INFO ==="
          uname -a
          cat /etc/*release || true

          echo "=== SHELLS IN /bin ==="
          ls -la /bin | grep sh || echo "NO SH FOUND"

          echo "=== WHO AM I ==="
          whoami

      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 14.21.3
          # cache: 'npm'  #omit cache, for now

      # Downgrade npm to 6 (compatible with Node 14 and core-js)
      - name: Downgrade npm to 6
        run: npm install -g npm@6

      # Install dependencies
      - name: Install dependencies
        run: npm ci
        shell: bash

      # Run tests
      - name: Run tests
        run: npm test
        shell: bash

      # Build React project
      - name: Build project
        run: npm run build
        shell: bash

      # Deploy to FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.URL }}
          username: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.PASS }}
          protocol: ftp
          local-dir: ./build       # Only upload production build
          server-dir: ${{ secrets.PATH }}
          include: |
            static/**
            images/**
            index.html
            asset-manifest.json
            robots.txt
            manifest.json
          # log-level: verbose    # optional

      # Success message
      - name: Signal Success
        run: echo '---- DEPLOY SUCCESSFUL ---'